spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: taesu
    password: password
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1

app:
  notification:
    consumer:
      exchange: app.notification
      instances:
        notification-email:
          routingKey: email
          topic: app.notification.email
          dlRoutingKey: email.dead
          dlTopic: app.notification.email.dead
        notification-sms:
          routingKey: sms
          topic: app.notification.sms
          dlRoutingKey: sms.dead
          dlTopic: app.notification.sms.dead
        notification-kakao:
          routingKey: kakao
          topic: app.notification.kakao
          dlRoutingKey: kakao.dead
          dlTopic: app.notification.kakao.dead
        notification-line:
          routingKey: line
          topic: app.notification.line
          dlRoutingKey: line.dead
          dlTopic: app.notification.line.dead
  orders:
    consumer:
      exchange: app.orders
      instances:
        orders-event:
          routingKey: event
          topic: app.orders.event
          dlRoutingKey: event.dead
          dlTopic: app.orders.event.dead
